-- Initialization script for PostgreSQL to support FastAPI Todos
-- This script creates required enum type and tables if they do not exist.

-- Create enum type for todo status (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'todo_status') THEN
        CREATE TYPE todo_status AS ENUM ('start', 'in_process', 'pending', 'done', 'cancel');
    END IF;
END $$;

-- Create todos table
CREATE TABLE IF NOT EXISTS public.todos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status todo_status NOT NULL DEFAULT 'pending'
);

-- Create auth_tokens table
CREATE TABLE IF NOT EXISTS public.auth_tokens (
    token varchar PRIMARY KEY,
    name varchar NULL,
    created_at timestamp without time zone NULL DEFAULT CURRENT_TIMESTAMP,
    active integer NOT NULL DEFAULT 1
);

-- Optional: basic indexes (kept minimal)
-- CREATE INDEX IF NOT EXISTS idx_todos_status ON public.todos (status);
